dictionary/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers
from django.conf.urls.static import static



router = routers.DefaultRouter()
# register job endpoint in the router
router.register(r'jobs', views.JobViewSet)

app_name = 'dictionary'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^upload_file/$', views.upload_file, name='upload_file'),
    url(r'^explore_words/(?P<source_id>.*)/$', views.explore_new_words, name='explore_words'),
    url(r'^explore_words/$', views.explore_new_words, name='explore_words'),
    url(r'^sources/$', views.source_types, name='sources'),
    url(r'^new_words/(?P<job_id>.*)/$', views.new_words, name='new_words'),
    url(r'^poll_state$', views.poll_state, name='poll_state'),
    url(r'^router/', include(router.get_urls())),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_definition/', views.get_definition, name='get_definition'),
    url(r'^get_usage/', views.get_usage, name='get_usage'),
    url(r'^save_word/', views.save_word, name='save_word'),
    url(r'^source_words/(?P<source_id>.*)/(?P<status_filter>.*)/$', views.source_words, name='source_words'),
    url(r'^source_words/(?P<source_id>.*)/$', views.source_words, name='source_words'),

]

lexicon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from lexicon import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dictionary/', include('dictionary.urls')),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/accounts/login'}, name='logout'),
    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/register/complete/$', views.registration_complete, name='registration_complete'),


]

dictionary/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.files.storage import default_storage

NEW, LEARN, KNOWN, IGNORE = 0, 1, 2, 3
WORD_STATUSES = ((NEW, 'new'),
                 (LEARN, 'learn'),
                 (KNOWN, 'known'),
                 (IGNORE, 'ignore'))


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class TextFile(models.Model):
    #type = models.ForeignKey(Source)
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to=user_directory_path)
    upload_date = models.DateTimeField('upload date')
    new_words_count = models.IntegerField(default=0)
    total_words_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.id:
            self.upload_date = timezone.now()
        return super(TextFile, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Word(models.Model):
    user = models.ForeignKey(User)
    word = models.CharField(max_length=200)
    explore_date = models.DateTimeField('explore date')
    status = models.IntegerField(choices=WORD_STATUSES, default=NEW)
    source = models.ManyToManyField(TextFile)

    def __str__(self):
        return self.word

    def save(self, *args, **kwargs):
        if not self.id:
            self.explore_date = timezone.now()
        return super(Word, self).save(*args, **kwargs)


class Dictionary(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()


class Meaning(models.Model):
    word = models.ForeignKey(Word, primary_key=True, on_delete=models.CASCADE)
    #dictionary = models.ForeignKey(Dictionary)
    meaning = models.TextField(max_length=10000)

    def __str__(self):
        return self.meaning


class Source(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Usage(models.Model):
    word = models.ForeignKey(Word)
    source = models.ForeignKey(TextFile)
    usage = models.TextField()


class SubUsage(models.Model):
    word = models.ForeignKey(Word)
    source = models.ForeignKey(TextFile)
    usage = models.TextField()
    begin_time = models.TextField()
    end_time = models.TextField()
    block_id = models.IntegerField()


class Job(models.Model):
    """Class describing a computational job"""

    # currently, available types of job are:
    TYPES = (
        ('fibonacci', 'fibonacci'),
        ('power', 'power'),
    )

    # list of statuses that job can have
    STATUSES = (
        ('pending', 'pending'),
        ('started', 'started'),
        ('finished', 'finished'),
        ('failed', 'failed'),
    )

    type = models.CharField(choices=TYPES, max_length=20)
    status = models.CharField(choices=STATUSES, max_length=20)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    argument = models.PositiveIntegerField()
    result = models.IntegerField(null=True)

    def save(self, *args, **kwargs):
        """Save model and if job is in pending state, schedule it"""
        super(Job, self).save(*args, **kwargs)
        if self.status == 'pending':
            from .tasks import TASK_MAPPING
            task = TASK_MAPPING[self.type]
            task.delay(job_id=self.id, n=self.argument)

dictionary/forms.py
from django import forms
from .models import TextFile
from django.forms import ModelForm


class UploadFileForm(ModelForm):
    class Meta:
        model = TextFile
        fields = ['title', 'file']

dictionary/views.py
from django.shortcuts import render
from .models import Word, Source, TextFile, Meaning, NEW, KNOWN, SubUsage, LEARN
from .forms import UploadFileForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Count
from .models import Job
from .serializers import JobSerializer
from .tasks import get_file_words
from django.views.decorators.csrf import csrf_exempt
from celery.result import AsyncResult
from lexicon.celeryconf import app
from django.http import HttpResponse
import json
from translator import parser
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from rest_framework import mixins, viewsets


@login_required()
def index(request):
    last_words = Word.objects.filter(status=1).filter(user=request.user).order_by('-explore_date')[:30]
    total = Word.objects.filter(user=request.user).count()
    new = Word.objects.filter(status=NEW).filter(user=request.user).count()
    definition = {}
    for word in last_words:
        meaning = Meaning.objects.filter(word=word.id)
        definition[word] = json.loads(str(meaning[0])) if meaning else None
    return render(request, 'dictionary/index.html', context={'words': definition,
                                                             'total': total,
                                                             'new': new,
                                                             'last_learned': last_words,
                                                             'username': request.user})


@login_required()
def explore_new_words(request, source_id=None):
    new_words = Word.objects.filter(status=NEW).filter(user=request.user) if not source_id else Word.objects.filter(status=NEW).filter(user=request.user).filter(source__id=source_id)
    return render(request, 'dictionary/word_explorer.html', context={'new_words': [str(word) for word in new_words]})


@csrf_exempt
def get_definition(request):
    if request.is_ajax():
        if 'word' in request.POST.keys() and request.POST['word']:
            data = parser.get_word_definition(request.POST['word'])
        else:
            data = 'No word in the request'
    else:
        data = 'This is not an ajax request'
    json_data = json.dumps(data)
    print(json_data)
    return HttpResponse(json_data, content_type='application/json')


@csrf_exempt
def get_usage(request):
    if request.is_ajax():
        if 'word' in request.POST.keys() and request.POST['word']:
            word = Word.objects.get(word=request.POST['word'])
            usages = SubUsage.objects.filter(word=word)
            data = {}
            for usage in usages:
                if usage.source.title not in data:
                    data[usage.source.title] = [usage.usage]
                else:
                    data[usage.source.title].append(usage.usage)
        else:
            data = 'No word in the request'
    else:
        data = 'This is not an ajax request'
    json_data = json.dumps(data)
    print(json_data)
    return HttpResponse(json_data, content_type='application/json')


@csrf_exempt
def save_word(request):
    expected_fields = ['word', 'meaning', 'status']
    has_all_data = True
    if request.is_ajax():
        # for field in expected_fields:
            # if field not in request.POST.keys() or request.POST[field] is None:
            #     print('Cannot save word. Missing requared data. Post body: ' + str(request.POST))
            #     has_all_data =False
        # if has_all_data:
        word = Word.objects.get(word=request.POST['word'])
        word.status = request.POST['status']
        word.save()
        # if request.POST['status'] == 'learn':
        #     meaning = Meaning(word=request.POST['word'], meaning=request.POST['meaning'])
        #     meaning.save()
    else:
        data = 'This is not an ajax request'
    return HttpResponse({'Status': 'Ok'}, content_type='application/json')


@login_required()
def source_types(request):
    data = []
    last_uploaded_sources = TextFile.objects.filter(user=request.user).order_by('-upload_date')[:30]
    for source in last_uploaded_sources:
        unprocessed = Word.objects.filter(status=NEW).filter(user=request.user).filter(source__id=source.id).count()
        to_learn = Word.objects.filter(status=LEARN).filter(user=request.user).filter(source__id=source.id).count()
        data.append((source, unprocessed, to_learn))
    return render(request, 'dictionary/source_list.html', context={'sources': data})


@login_required()
def source_words(request, source_id, status_filter=-1):
    source = TextFile.objects.get(id=source_id)
    words = Word.objects.filter(source=source).filter(user=request.user)
    return render(request, 'dictionary/source.html', context={'words': enumerate(words),
                                                              'source': source,
                                                              'word_status_filter': status_filter})


@login_required()
@csrf_exempt
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            #source_type = [source for source in source_types_all if str(source.id) == request.POST['source']]
            #if not source_type:
            #    raise Exception('Invalid source type ' + request.POST['source'])
            #instance = TextFile(type=source_type[0], title=request.POST['title'], file=request.FILES['file'])
            if request.POST['title']:
                pass
            text_file = TextFile(title=request.POST['title'], file=request.FILES['file'], user=request.user)
            text_file.save()
            #job_id = get_file_words.delay(instance.id)
            known_words = [x.word for x in Word.objects.filter(user=request.user)]
            with open(text_file.file.path) as f:
                sub_parser = parser.SrtSubParser(f)
                words = sub_parser.get_words()
            unknown_words = [Word(word=word, user=request.user, explore_date=timezone.now()) for word in words if word not in known_words]
            Word.objects.bulk_create(unknown_words)
            for new_word in unknown_words:
                new_word.source.add(text_file)
            text_file.new_words_count = len(unknown_words)
            text_file.total_words_count = len(words)
            text_file.save()
            # Save usages
            usages_to_save = []
            for word in unknown_words:
                for usage in words[word.word]:
                    usages_to_save.append(SubUsage(word=word,
                                                   source=text_file,
                                                   usage=usage.line,
                                                   begin_time=usage.begin_time,
                                                   end_time=usage.end_time,
                                                   block_id=usage.block_id
                    ))
            SubUsage.objects.bulk_create(usages_to_save)
            return render(request, 'dictionary/upload_statistics.html', context={'words': unknown_words})
    else:
        form = UploadFileForm()
    return render(request, 'dictionary/upload.html', {'form': form}) #, 'sources': source_types_all})


@login_required()
def new_words(request, job_id):
    return render(request, 'dictionary/new_words.html', {'task_id': job_id})


@csrf_exempt
def poll_state(request):
    """ A view to report the progress to the user """
    if request.is_ajax():
        print("Is ajax")
        if 'task_id' in request.POST.keys() and request.POST['task_id']:
            task_id = request.POST['task_id']
            task = app.AsyncResult(task_id)

            print(task)
            data = task.result or task.state
        else:
            data = 'No task_id in the request'
    else:
        data = 'This is not an ajax request'

    json_data = json.dumps(data)
    print(json_data)
    return HttpResponse(json_data, content_type='application/json')


class JobViewSet(mixins.CreateModelMixin,
                 mixins.ListModelMixin,
                 mixins.RetrieveModelMixin,
                 viewsets.GenericViewSet):
    """
    API endpoint that allows jobs to be viewed or created.
    """
    queryset = Job.objects.all()
    serializer_class = JobSerializer

dictionary/templates/dictionary/base.html
{% load static %}
<link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dictionary/jquery-1.9.1.min.js' %}"></script>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'dictionary:home' %}">Dictionary</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'dictionary:home' %}">Home</a></li>
      <li><a href="{% url 'dictionary:upload_file' %}">Upload file</a></li>
      <li><a href="{% url 'dictionary:sources' %}">View sources</a></li>
        <li class=".pull-right"><a href="{% url 'logout' %}">Logout</a></li>
      <!--<li><a href="#">Page 3</a></li>-->
    </ul>
      <div>
          <p>{{ username }}</p>
      </div>
  </div>
</nav>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
        {% block content %}
        {% endblock %}
        </div>
    </div>
</div>

dictionary/templates/dictionary/index.html
{% extends 'base.html' %}

{% block content %}
Words in your dictionary - {{ total }} <br>
Waiting to be learn - <a href="{% url 'dictionary:explore_words' %}">{{ new }}</a>
{% if last_learned %}
    <ul>
    {% for word, meaning in last_learned.items %}
        <li>{{ word }}</li>
        <ul>
        {% for spart, means in meaning.items %}
            <li><div> {{ spart }}: </div></li>
            <ul>
            {% for mean in means %}
            <li><div> {{ mean }} </div></li>
            {% endfor %}
            </ul>
        {% endfor %}
        </ul>
    {% endfor %}
    </ul>
{% endif %}

{%if last_learned %}
    Last added words:
    <ul>
    {% for word in last_learned %}
        <li>{{ word.word }}</li>
        <div> {{ word.meaning }} </div>
    {% endfor %}
    </ul>
{% else %}
    <p>You dictionary is empty. Would you like to add any words?</p>
{% endif %}
{% endblock content %}

dictionary/templates/dictionary/new_words.html
<!DOCTYPE html>
<html>
<head>
 <title>Celery testing</title>
 <!--<script src="{{ STATIC_URL }}js/jquery-1.10.1.min.js"></script>-->
    <script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
 <style>
  .progress {
   width:50%;
   background:yellow;
  }
  .bar {
   height:15px;
   width:0%;
   background:tomato;
   text-align:right;
  }
 </style>
</head>
<body>
 <h1>Upload new words from file!</h1>

 <div id="container">

  <div class="progress_container">

   <div class="current-task">
    <h4>{% if task_id %} Task ID: {{ task_id }} {% endif %}</h4>
   </div>

   <div class="status"></div>
   {% if task_id %}
   <div class="progress">
    <div class="bar"></div>
   </div>
   {% endif %}
  </div>

 </div>
 {% if task_id %}
 <script type="text/javascript">
  jQuery(document).ready(function() {

   // pole state of the current task
   var PollState = function(task_id) {
    jQuery.ajax({
     url: "/dictionary/poll_state",
     type: "POST",
     data: "task_id=" + task_id,
        cache: false,
    }).done(function(task){
     console.log(task);
     if (task.process_percent) {
      jQuery('.bar').css({'width': task.process_percent + '%'});
      jQuery('.bar').html( task.process_percent + '%')
     } else {
      jQuery('.status').html(task);
     };

     // create the infinite loop of Ajax calls to check the state
     // of the current task
     //PollState(task_id);
    if (task.process_percent >= 100) {
      clearTimeout();
    } else {
      setTimeout(function(){PollState(task_id);}, 5000);
    }
    });
   }

      PollState('{{ task_id }}');
  });
 </script>
 {% endif %}

</body>
</html>

dictionary/templates/dictionary/source.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
    <script src="{% static 'dictionary_app.js' %}"></script>
{% endblock %}

{% block content %}
{% if words %}
<head>
    <script src="words_state.js" type="text/javascript"></script>
</head>
<body>
<script type="text/javascript">
window.onload = function () {
    console.log('Onload func')
    var filter_status = {{ word_status_filter }}
    console.log(filter_status)
    if (filter_status >= 0){
        filter_words(filter_status)
        document.getElementById('filters').style.display = 'none';
    }
};

var save_word = function (word, status) {
    console.log(status);
   jQuery.ajax({
       url: "/dictionary/save_word/",
       type: "POST",
       data: {"word": word, "status": status},
       cache: false
   })
};

var filter_words = function (status) {
    var i = 0;
    while (document.getElementById('status_' + i) != null){
        var element = document.getElementById('status_' + i);

        if (parseInt(element.innerHTML) != parseInt(status) && parseInt(status)>=0) {
            element.parentNode.style.display='none';
        } else {
            element.parentNode.style.display='';
        }
        i+=1;
    }
};

var change_word_status = function(word, status, id) {
    save_word(word, status);
    var status_td = document.getElementById('status_' + id)
    status_td.innerHTML = status
};

var details_toggle = function (id) {
    var details_div = document.getElementsByName('details')[parseInt(id)];
    if (details_div.style.display == '') {
        details_div.style.display='none';
    } else {
        details_div.style.display='';
        var word = document.getElementsByName('word')[id].innerText;
        console.log(word);
        get_server_word_info('get_definition', word, display_word_definition, 'meaning_' + id);
        get_server_word_info('get_usage', word, display_word_usage, 'usage_' + id);
    }


};

var highlight_word = function (highlighted_mode, id){
    var word = document.getElementsByName('word_link')[id];
    if (highlighted_mode) {
        word.style.color = 'red';
        word.style.fontWeight="bold";
    } else {
        word.style.color = '';
        word.style.fontWeight="normal";
    }
};

</script>
</body>
<div id="filters">
    <h4>Filters: </h4>
<div class="radio-inline">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios1" value="-1" onclick="filter_words(-1)" checked>
    All
  </label>
</div>
<div class="radio-inline">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios2" value="0" onclick="filter_words(0)">
    New
  </label>
</div>
<div class="radio-inline">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios3" value="2" onclick="filter_words(2)">
    Known
  </label>
</div>
<div class="radio-inline">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios3" value="1" onclick="filter_words(1)">
    To learn
  </label>
</div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">Word</div>
        <div class="col-md-2">Status</div>
        <div class="col-md-4">Actions</div>
    </div>
    {% for i, word in words %}
    <div class="row" id="{{ i }}" onmouseover="highlight_word(true, {{ i }} )" onmouseout="highlight_word(false, {{ i }} )">
        <div id="word_{{ i }}" name="word" class="col-md-4">
            <a name="word_link" id="{{ i }}" onclick="details_toggle( {{ i }} )" > {{ word.word }} </a>
        </div>
        <div id="status_{{ i }}" name="status" class="col-md-2">{{ word.status }}</div>
        <div class="container">
        <div class="col-md-1">
            <a id="save" onclick="change_word_status('{{ word.word }}', 1, {{ i }})" >Save</a>
        </div>
        <div class="col-md-1">
            <a id="known"  onclick="change_word_status('{{ word.word }}', 2, {{ i }})">Known</a>
        </div>
        <div class="col-md-1">
            <a id="ignore" onclick="change_word_status('{{ word.word }}', 3, {{ i }})">Ignore</a>
        </div>
            </div>
    </div>
    <div name="details" id="{{ i }}" class="row" style="display: none">
        <h3>Definition:</h3>
        <div name="meaning" id="meaning_{{ i }}">
            Getting meaning from online sources...
        </div>
        <h3>Usage examples:</h3>
        <div  name="usage" id="usage_{{ i }}">
            Getting usage from online sources...
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
    <p>There is no new words in source.</p>
{% endif %}
{% endblock content %}

dictionary/templates/dictionary/source_list.html
{% extends 'base.html' %}

{% block content %}
{% if sources %}
<table class="table table-striped">
            <tr>
            <td>Upload date</td>
            <td>Title</td>
            <td>Total words count</td>
            <td>New words count</td>
            <td>Unprocessed words</td>
            <td>Words to learn</td>
        </tr>
    {% for source, unprocessed, to_learn in sources %}
        <tr>
        <td>{{ source.upload_date }}</td>
            <td><a href="{% url 'dictionary:source_words' source.id %}">{{ source.title }}</a></td>
            <td>{{ source.total_words_count }} </td>
            <td>{{ source.new_words_count }}</td>
            <td><a href="{% url 'dictionary:explore_words' source.id %}">{{ unprocessed }}</a></td>
            <td><a href="{% url 'dictionary:source_words' source.id 1 %}">{{ to_learn }}</a></td>
    {% endfor %}
        </tr>
    </table>
{% else %}
    <p>There is no uploaded sources.</p>
{% endif %}
{% endblock content %}

dictionary/templates/dictionary/upload.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
 <script type="text/javascript">
     jQuery(document).ready(function () {
         document.getElementById("id_file").onchange = function () {
         document.getElementById("id_title").value = document.getElementById("id_file").files[0].name
     }

       }
       )

 </script>
<form class="form-inline"  method="post" action="{% url 'dictionary:upload_file' %}" enctype="multipart/form-data">{% csrf_token %}
    <label for="id_file">Choose file to upload: </label>
    <input class="form-control" id="id_file" name="file" type="file" required="">
    <label for="id_title">Title:</label>
    <input class="form-control" id="id_title" maxlength="200" name="title" type="text" required="">
    <input class="btn btn-primary" type="submit" value="Upload">
</form>
{% endblock content %}

dictionary/templates/dictionary/upload_statistics.html
{% extends 'base.html' %}

{% block content %}
Uploaded new {{ words|length }} words.
{% endblock content %}

dictionary/templates/dictionary/word_explorer.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'dictionary_app.js' %}"></script>
{% endblock %}
{% block content %}
{% load static %}
    <script type="text/javascript" >
        var i = 0;
        var words = [];
        var word = null;
        var meaning = null;
        var translation = null;

       var getWordSynonym = function(word) {
       jQuery.ajax({
           url: "/dictionary/get_synonym/",
           type: "POST",
           data: "word=" + word,
           cache: false,
           timeout: 5000,
           success: function (res) {
               var el = document.getElementById('usage')
               while (el.firstChild) el.removeChild(el.firstChild);
               usages = res;
                for (var source in usages){
                    var header_div = document.createElement('div');
                    header_div.innerHTML = source;
                    for (var usage in usages[source]) {
                        var usage_div = document.createElement('div');
                        usage_div.innerHTML = usages[source][usage]
                        header_div.appendChild(usage_div)
                }
                }
                el.appendChild(header_div)

               console.log(usage)

           },
           error: function (res) {
               console.log('Error');
               document.getElementById('usage').innerHTML='Failed to get usage.'

           }

       })
       };

       function display_word() {
           if (i < words.length) {
               word = words[i];
               i ++;
               get_server_word_info('get_definition', word, display_word_definition, 'meaning');
               get_server_word_info('get_usage', word, display_word_usage, 'usage');
               get_server_word_info('translate', word, display_word_translation, 'translate');
//               meaning = display_word_definition('meaning', word);
//               translation = translateWord(word);
//               display_word_usage('usage', word)
               document.getElementById('word').innerHTML = word;
           } else {
               word = null;
               document.getElementById('word').innerHTML = 'No more new words'
           }

       }

       jQuery(document).ready(function () {
           words = {{ new_words | safe }};
           display_word()

       });

       function skip() {
           document.getElementById('skip').onclick = function () {
//               i++;
               //words.unshift(word)
               console.log(words[i])
               display_word()
           }
       }

       function save() {
           document.getElementById('save').onclick = function () {
               // TODO save word with status 'to learn'
               var meaning_json = JSON.stringify(meaning);
               console.log(meaning_json);
               save_word(word, meaning_json, status=1);
               display_word()
           }
       }
       function known() {
           document.getElementById('known').onclick = function () {
               // TODO save word with status 'to learn'
               var meaning_json = JSON.stringify(meaning)
               console.log(meaning_json)
               save_word(word, meaning_json, status=2)
               display_word()
           }
       }

       function ignore() {
           document.getElementById('ignore').onclick = function () {
               // TODO save word with status 'to learn'
               save_word(word, '', status=3);
               display_word()
           }
       }
       function back() {
           document.getElementById('back').onclick = function () {
                i -= 2;
               display_word()
           }
       }
       // TODO: configuration via UI. Remove hardcoded defaults to User config
       document.addEventListener("keyup", function(event) {
            console.log(event.keyCode)
            event.preventDefault();
            switch (event.keyCode){
                case (83): {
                    document.getElementById("save").click();
                    break;
                }
                case (75): {
                    document.getElementById("known").click();
                    break;
                }
                case (73): {
                    document.getElementById("ignore").click();
                    break;
                }
                case (37): {
                    document.getElementById("back").click();
                    break;
                }
                case (39): {
                    document.getElementById("skip").click();
                    break;
                }
            }
        });
</script>


<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h2 id="word"></h2>
                <div class="row">
    <div class="col-md-8">
        <h3>Definition:</h3>
      <div class="row" id="meaning">
          Getting meaning from online sources...
      </div>
        <h3>Usage examples:</h3>
        <div class="row" id="usage">
          Getting usage from online sources...
      </div>
        <h3>Translation:</h3>
        <div class="row" id="translate">
          Getting translate from online sources...
      </div>
    </div>
        </div>
        </div>
    <div class="col-md-2">
        <div class="row"><button id="skip" type="button" class="btn btn-info btn-block" onclick="skip()">Skip</button></div>
    <div class="row"><button id="save" type="button" class="btn btn-success btn-block" onclick="save()">Save</button></div>
    <div class="row"><button id="known" type="button" class="btn btn-warning btn-block" onclick="known()">Known</button></div>
    <div class="row"><button id="ignore" type="button" class="btn btn-danger btn-block" onclick="ignore()">Ignore</button></div>
    <div class="row"><button id="back" type="button" class="btn btn-primary btn-block" onclick="back()">Previous word</button></div>
    </div>
    </div>



</div>
{% endblock content %}